### ISSUE TITLE
Scope of the account service 

### ISSUE THREAD

**Issue by p5150j** [ProjectLibertyLabs/gateway#3]
## Account Service Requirements

- [x] Must provide endpoint(s) for the creation and delegation of accounts
- [x] Must provide an endpoint for claiming handles
- [x] Must provide an endpoint for the request for Private Graph Keys
- [x] Must provide an interface for Web3 Wallet Interactions
- [ ] ~~May provide a service for handling sessions~~

## Outputs

- [x] AmplicaLabs/account-service#2
- [x] AmplicaLabs/account-service#1
- [x] AmplicaLabs/account-service#3
